export const API_ENDPOINTS = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    setPassword: "/auth/set-password",
  },
  admin: {
    teachers: "/admin/teachers",
    teacher: (id: string) => `/admin/teachers/${id}`,
    teacherActions: (id: string) => `/admin/teachers/${id}/actions`,
    students: "/admin/students",
    student: (id: string) => `/admin/students/${id}`,
    studentPhoto: (id: string) => `/admin/students/${id}/photo`,
    parents: "/admin/parents",
    parent: (id: string) => `/admin/parents/${id}`,
    parentActions: (id: string) => `/admin/parents/${id}/actions`,
    programmes: "/admin/programmes",
    programme: (id: string) => `/admin/programmes/${id}`,
    teachingAssignments: "/admin/teaching-assignments",
    teachingAssignment: (id: string) => `/admin/teaching-assignments/${id}`,
    lessonRequests: "/admin/lesson-requests",
    lessonRequest: (id: string) => `/admin/lesson-requests/${id}`,
    lessonRequestPublish: (id: string) =>
      `/admin/lesson-requests/${id}/publish`,
    sessions: "/admin/sessions",
    session: (id: string) => `/admin/sessions/${id}`,
    contactInquiry: (id: string) => `/admin/contact-inquiries/${id}`,
    tutorApplications: "/admin/tutor-applications",
    tutorApplication: (id: string) => `/admin/tutor-applications/${id}`,
    tutorApplicationActions: (id: string) =>
      `/admin/tutor-applications/${id}/actions`,
  },
  teacher: {
    sessions: "/teacher/sessions",
    session: (id: string) => `/teacher/sessions/${id}`,
    sessionAttendance: (id: string) => `/teacher/sessions/${id}/attendance`,
  },
  parent: {
    student: (id: string) => `/parent/students/${id}`,
    studentPhoto: (id: string) => `/parent/students/${id}/photo`,
  },
  profile: {
    root: "/profile",
    avatar: "/profile/avatar",
    password: "/profile/password",
  },
} as const;
