-- Applied to the hosted project. Parent accounts, guardian links, and audit logging.
create type public.parent_onboarding_status as enum ('invited','active');
create type public.guardian_relationship as enum ('mother','father','guardian','foster_parent','other');
create table public.parents (id uuid primary key references public.profiles(id) on delete cascade,occupation text,onboarding_status public.parent_onboarding_status not null default 'invited',invited_at timestamptz not null default now(),activated_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint parents_occupation_length_check check (occupation is null or char_length(occupation) <= 100));
create table public.student_parents (student_id uuid not null references public.students(id) on delete cascade,parent_id uuid not null references public.parents(id) on delete cascade,relationship public.guardian_relationship not null,is_primary_contact boolean not null default false,created_at timestamptz not null default now(),primary key(student_id,parent_id));
create unique index student_parents_one_primary_per_student_idx on public.student_parents(student_id) where is_primary_contact;
create index student_parents_parent_id_idx on public.student_parents(parent_id);
create table public.audit_logs (id bigint generated by default as identity primary key,actor_id uuid references public.profiles(id) on delete set null,action text not null,entity_type text not null,entity_id text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
alter table public.parents enable row level security; alter table public.student_parents enable row level security; alter table public.audit_logs enable row level security;
revoke all on public.parents,public.student_parents,public.audit_logs from anon,authenticated; grant all on public.parents,public.student_parents,public.audit_logs to service_role;
create trigger parents_set_updated_at before update on public.parents for each row execute function private.set_updated_at();
