import { createAdminClient } from "@/lib/supabase/admin";
import { sanitizeFilterTerm } from "@/lib/repositories";
import type { CreateParentRequest,UpdateParentRequest } from "@/modules/parents/schemas";
import type { GuardianRelationship } from "@/modules/parents/types";
const SELECT="id,occupation,onboarding_status,invited_at,activated_at,created_at,updated_at,profiles!inner(first_name,last_name,email,phone,address,status),student_parents(student_id,relationship,is_primary_contact,students(id,admission_number,first_name,middle_name,last_name))" as const;
export function listParentRows(from:number,to:number,search?:string,status?:string){const admin=createAdminClient();const term=sanitizeFilterTerm(search);let q=admin.from("parents").select(SELECT,{count:"exact"}).order("created_at",{ascending:false}).range(from,to);if(status&&status!=="all")q=q.eq("onboarding_status",status as "invited"|"active");if(term)q=q.or(`occupation.ilike.%${term}%,profiles.first_name.ilike.%${term}%,profiles.last_name.ilike.%${term}%,profiles.email.ilike.%${term}%`);return q;}
export function getParentRow(id:string){return createAdminClient().from("parents").select(SELECT).eq("id",id).maybeSingle();}
export function getParentCount(filters?:{onboarding?:"invited"|"active";account?:"suspended"}){let q=createAdminClient().from("parents").select("id,profiles!inner(status)",{count:"exact",head:true});if(filters?.onboarding)q=q.eq("onboarding_status",filters.onboarding);if(filters?.account)q=q.eq("profiles.status",filters.account);return q;}
export async function configureParentProfile(id:string,input:CreateParentRequest){return createAdminClient().from("profiles").update({first_name:input.firstName.trim(),last_name:input.lastName.trim(),email:input.email.trim().toLowerCase(),phone:input.phone?.trim()||null,address:input.address?.trim()||null,role:"parent",status:"active"}).eq("id",id).select("id").single();}
export function createParentRecord(id:string,input:CreateParentRequest){return createAdminClient().from("parents").insert({id,occupation:input.occupation?.trim()||null}).select("id").single();}
export function replaceStudentLinks(parentId:string,students:{studentId:string;relationship:GuardianRelationship;isPrimaryContact:boolean}[]){const admin=createAdminClient();return (async()=>{const del=await admin.from("student_parents").delete().eq("parent_id",parentId);if(del.error)return del;if(!students.length)return del;return admin.from("student_parents").insert(students.map(s=>({parent_id:parentId,student_id:s.studentId,relationship:s.relationship,is_primary_contact:s.isPrimaryContact})));})();}
export async function updateParentRecord(id:string,input:UpdateParentRequest){const admin=createAdminClient();const p=await admin.from("profiles").update({first_name:input.firstName.trim(),last_name:input.lastName.trim(),phone:input.phone?.trim()||null,address:input.address?.trim()||null}).eq("id",id);if(p.error)return p;return admin.from("parents").update({occupation:input.occupation?.trim()||null}).eq("id",id).select("id").single();}
export function updateParentAccountStatus(id:string,status:"active"|"inactive"|"suspended"){return createAdminClient().from("profiles").update({status}).eq("id",id).select("id").single();}
export function markParentActivated(id:string){return createAdminClient().from("parents").update({onboarding_status:"active",activated_at:new Date().toISOString()}).eq("id",id).eq("onboarding_status","invited").select("id").single();}
export function listStudentOptions(){return createAdminClient().from("students").select("id,admission_number,first_name,middle_name,last_name,status").order("first_name").limit(500);}

export function getStudentParentRows(studentId:string){return createAdminClient().from("student_parents").select("relationship,is_primary_contact,parents!inner(id,occupation,onboarding_status,profiles!inner(first_name,last_name,email,phone,status))").eq("student_id",studentId).order("is_primary_contact",{ascending:false});}
