import { createAdminClient } from "@/lib/supabase/admin";
import type { TablesInsert,TablesUpdate } from "@/types/database";
import { sanitizeFilterTerm } from "@/lib/repositories";
const SELECT="id,cohort_id,title,description,session_date,start_time,end_time,meeting_link,status,created_by,created_at,updated_at,cohorts!inner(id,code,name,teaching_assignments!inner(teacher_id,programmes!inner(id,name),teachers!inner(profiles!inner(first_name,last_name,email)))),session_attendance(status)" as const;
export function listSessionRows(from:number,to:number,f:{search?:string;status?:string;cohortId?:string;teacherId?:string;programmeId?:string;dateFrom?:string;dateTo?:string}){let q=createAdminClient().from("class_sessions").select(SELECT,{count:"exact"}).order("session_date",{ascending:false}).order("start_time",{ascending:false}).range(from,to);if(f.search){const s=sanitizeFilterTerm(f.search);q=q.or(`title.ilike.%${s}%,description.ilike.%${s}%`)}if(f.status&&f.status!=="all")q=q.eq("status",f.status as any);if(f.cohortId)q=q.eq("cohort_id",f.cohortId);if(f.teacherId)q=q.eq("cohorts.teaching_assignments.teacher_id",f.teacherId);if(f.programmeId)q=q.eq("cohorts.teaching_assignments.programme_id",f.programmeId);if(f.dateFrom)q=q.gte("session_date",f.dateFrom);if(f.dateTo)q=q.lte("session_date",f.dateTo);return q;}
export function getSessionRow(id:string){return createAdminClient().from("class_sessions").select(SELECT).eq("id",id).maybeSingle();}
export function insertSession(input:TablesInsert<"class_sessions">){return createAdminClient().from("class_sessions").insert(input).select(SELECT).single();}
export function updateSessionRow(id:string,input:TablesUpdate<"class_sessions">){return createAdminClient().from("class_sessions").update(input).eq("id",id).select(SELECT).single();}
export function countSessions(status?:string){let q=createAdminClient().from("class_sessions").select("id",{count:"exact",head:true});if(status)q=q.eq("status",status as any);return q;}
export function teacherOwnsCohort(cohortId:string,teacherId:string){return createAdminClient().from("cohorts").select("id,teaching_assignments!inner(teacher_id,status)").eq("id",cohortId).eq("teaching_assignments.teacher_id",teacherId).eq("teaching_assignments.status","active").in("status",["open","active"]).maybeSingle();}
