import { createAdminClient } from "@/lib/supabase/admin";
import type { TablesInsert,TablesUpdate } from "@/types/database";
import { sanitizeFilterTerm } from "@/lib/repositories";
const SELECT="id,lesson_assignment_id,title,description,session_date,start_time,end_time,meeting_link,status,created_by,created_at,updated_at,lesson_assignments!inner(id,teacher_id,student_id,programme_id,status,students(id,first_name,middle_name,last_name),programmes(id,name),teachers(id,profiles(first_name,last_name,email))),session_attendance(status),homework(status)" as const;
export function listSessionRows(from:number,to:number,f:{search?:string;status?:string;lessonAssignmentId?:string;teacherId?:string;programmeId?:string;dateFrom?:string;dateTo?:string}){let q=(createAdminClient() as any).from("class_sessions").select(SELECT,{count:"exact"}).not("lesson_assignment_id","is",null).order("session_date",{ascending:false}).order("start_time",{ascending:false}).range(from,to);if(f.search){const s=sanitizeFilterTerm(f.search);q=q.or(`title.ilike.%${s}%,description.ilike.%${s}%`)}if(f.status&&f.status!=="all")q=q.eq("status",f.status);if(f.lessonAssignmentId)q=q.eq("lesson_assignment_id",f.lessonAssignmentId);if(f.teacherId)q=q.eq("lesson_assignments.teacher_id",f.teacherId);if(f.programmeId)q=q.eq("lesson_assignments.programme_id",f.programmeId);if(f.dateFrom)q=q.gte("session_date",f.dateFrom);if(f.dateTo)q=q.lte("session_date",f.dateTo);return q;}
export function getSessionRow(id:string){return (createAdminClient() as any).from("class_sessions").select(SELECT).eq("id",id).maybeSingle();}
export function insertSession(input:TablesInsert<"class_sessions">){return (createAdminClient() as any).from("class_sessions").insert(input).select(SELECT).single();}
export function updateSessionRow(id:string,input:TablesUpdate<"class_sessions">){return (createAdminClient() as any).from("class_sessions").update(input).eq("id",id).select(SELECT).single();}
export function countSessions(status?:string){let q=(createAdminClient() as any).from("class_sessions").select("id",{count:"exact",head:true}).not("lesson_assignment_id","is",null);if(status)q=q.eq("status",status);return q;}
export function teacherOwnsLessonAssignment(id:string,teacherId:string){return (createAdminClient() as any).from("lesson_assignments").select("id,teacher_id,status").eq("id",id).eq("teacher_id",teacherId).eq("status","active").maybeSingle();}
