create type public.cohort_status as enum ('draft','open','active','completed','archived');
create type public.cohort_membership_status as enum ('active','transferred','completed','withdrawn');
create table private.cohort_code_counters(prefix text primary key,last_serial integer not null default 0,updated_at timestamptz not null default now(),constraint cohort_code_counters_prefix_check check(prefix ~ '^[A-Z0-9]{3,6}$'),constraint cohort_code_counters_serial_check check(last_serial>=0));
revoke all on private.cohort_code_counters from public,anon,authenticated;
create table public.cohorts(id uuid primary key default gen_random_uuid(),teaching_assignment_id uuid not null references public.teaching_assignments(id) on delete restrict,code text not null,name text not null,description text,capacity integer not null default 20,start_date date not null,expected_end_date date,status public.cohort_status not null default 'draft',created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint cohorts_code_not_blank check(length(btrim(code))>0),constraint cohorts_name_not_blank check(length(btrim(name))>0),constraint cohorts_name_length_check check(char_length(name)<=120),constraint cohorts_capacity_check check(capacity between 1 and 1000),constraint cohorts_date_order_check check(expected_end_date is null or expected_end_date>=start_date));
create unique index cohorts_code_unique_idx on public.cohorts(code);create unique index cohorts_assignment_name_lower_unique_idx on public.cohorts(teaching_assignment_id,lower(name));
create table public.cohort_students(id uuid primary key default gen_random_uuid(),cohort_id uuid not null references public.cohorts(id) on delete restrict,student_id uuid not null references public.students(id) on delete restrict,status public.cohort_membership_status not null default 'active',joined_at timestamptz not null default now(),left_at timestamptz,assigned_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint cohort_students_unique_membership unique(cohort_id,student_id));
create or replace function private.assign_cohort_code() returns trigger language plpgsql security definer set search_path='' as $$ declare v_slug text;v_prefix text;v_next_serial integer;begin if new.code is not null and btrim(new.code)<>'' then return new;end if;select p.slug into v_slug from public.teaching_assignments ta join public.programmes p on p.id=ta.programme_id where ta.id=new.teaching_assignment_id;v_prefix:=upper(substr(regexp_replace(v_slug,'[^a-zA-Z0-9]','','g'),1,3));if char_length(v_prefix)<3 then v_prefix:=rpad(v_prefix,3,'X');end if;insert into private.cohort_code_counters as counters(prefix,last_serial,updated_at) values(v_prefix,1,now()) on conflict(prefix) do update set last_serial=counters.last_serial+1,updated_at=now() returning last_serial into v_next_serial;new.code:=format('%s-%s',v_prefix,lpad(v_next_serial::text,3,'0'));return new;end;$$;
create trigger cohorts_assign_code before insert on public.cohorts for each row execute function private.assign_cohort_code();create trigger cohorts_set_updated_at before update on public.cohorts for each row execute function private.set_updated_at();create trigger cohort_students_set_updated_at before update on public.cohort_students for each row execute function private.set_updated_at();alter table public.cohorts enable row level security;alter table public.cohort_students enable row level security;revoke all on public.cohorts,public.cohort_students from anon,authenticated;grant all on public.cohorts,public.cohort_students to service_role;
