-- Hosted migration already applied. This local migration mirrors the enrolment review schema.
create type public.enrolment_application_status as enum ('pending','under_review','approved','rejected','withdrawn');
create type public.programme_enrolment_status as enum ('active','completed','withdrawn');
create table public.enrolment_applications (id uuid primary key default gen_random_uuid(),parent_id uuid not null references public.parents(id) on delete restrict,existing_student_id uuid references public.students(id) on delete restrict,child_first_name text not null,child_last_name text not null,child_date_of_birth date not null,preferred_format text not null,parent_name text not null,email text not null,phone text not null,additional_information text,status public.enrolment_application_status not null default 'pending',reviewed_by uuid references public.profiles(id) on delete set null,reviewed_at timestamptz,review_notes text,approved_student_id uuid references public.students(id) on delete restrict,submitted_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint enrolment_child_dob_check check(child_date_of_birth<=current_date),constraint enrolment_preferred_format_check check(preferred_format in('in-person','online','blended')));
create table public.enrolment_application_programmes(application_id uuid not null references public.enrolment_applications(id) on delete cascade,programme_id uuid not null references public.programmes(id) on delete restrict,created_at timestamptz not null default now(),primary key(application_id,programme_id));
create table public.programme_enrolments(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id) on delete restrict,programme_id uuid not null references public.programmes(id) on delete restrict,application_id uuid references public.enrolment_applications(id) on delete set null,status public.programme_enrolment_status not null default 'active',enrolled_at timestamptz not null default now(),completed_at timestamptz,withdrawn_at timestamptz,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index programme_enrolments_one_active_idx on public.programme_enrolments(student_id,programme_id) where status='active';
create index enrolment_applications_status_idx on public.enrolment_applications(status,submitted_at desc);
create trigger enrolment_applications_set_updated_at before update on public.enrolment_applications for each row execute function private.set_updated_at();
create trigger programme_enrolments_set_updated_at before update on public.programme_enrolments for each row execute function private.set_updated_at();
alter table public.enrolment_applications enable row level security;alter table public.enrolment_application_programmes enable row level security;alter table public.programme_enrolments enable row level security;
revoke all on public.enrolment_applications,public.enrolment_application_programmes,public.programme_enrolments from anon,authenticated;grant all on public.enrolment_applications,public.enrolment_application_programmes,public.programme_enrolments to service_role;
-- The full transactional approve_enrolment_application function is maintained in the hosted migration and project docs.
create or replace function public.approve_enrolment_application(p_application_id uuid,p_assignments jsonb,p_reviewer_id uuid,p_review_notes text default null)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_application public.enrolment_applications%rowtype;v_student_id uuid;v_assignment jsonb;v_programme_id uuid;v_cohort_id uuid;v_requested_count integer;v_assignment_count integer;v_capacity integer;v_member_count integer;v_cohort_programme_id uuid;
begin
select * into v_application from public.enrolment_applications where id=p_application_id for update;if not found then raise exception 'Enrolment application not found';end if;
if v_application.status not in('pending'::public.enrolment_application_status,'under_review'::public.enrolment_application_status) then raise exception 'Only pending or under-review applications can be approved';end if;
if jsonb_typeof(p_assignments)<>'array' then raise exception 'Cohort assignments must be an array';end if;
select count(*) into v_requested_count from public.enrolment_application_programmes where application_id=p_application_id;select count(*) into v_assignment_count from jsonb_array_elements(p_assignments);if v_requested_count=0 or v_assignment_count<>v_requested_count then raise exception 'Every requested programme must have exactly one cohort assignment';end if;
v_student_id:=v_application.existing_student_id;
if v_student_id is null then insert into public.students(admission_number,first_name,last_name,date_of_birth,admission_date,status,notes) values('',btrim(v_application.child_first_name),btrim(v_application.child_last_name),v_application.child_date_of_birth,current_date,'active'::public.student_status,nullif(btrim(v_application.additional_information),'')) returning id into v_student_id;insert into public.student_parents(student_id,parent_id,relationship,is_primary_contact) values(v_student_id,v_application.parent_id,'guardian'::public.guardian_relationship,true) on conflict(student_id,parent_id) do nothing;end if;
for v_assignment in select value from jsonb_array_elements(p_assignments) loop v_programme_id:=(v_assignment->>'programmeId')::uuid;v_cohort_id:=(v_assignment->>'cohortId')::uuid;if not exists(select 1 from public.enrolment_application_programmes where application_id=p_application_id and programme_id=v_programme_id) then raise exception 'A cohort was supplied for a programme that was not requested';end if;select c.capacity,ta.programme_id into v_capacity,v_cohort_programme_id from public.cohorts c join public.teaching_assignments ta on ta.id=c.teaching_assignment_id where c.id=v_cohort_id and c.status in('open'::public.cohort_status,'active'::public.cohort_status) and ta.status='active'::public.teaching_assignment_status;if not found or v_cohort_programme_id<>v_programme_id then raise exception 'Selected cohort is not available for the requested programme';end if;select count(*) into v_member_count from public.cohort_students where cohort_id=v_cohort_id and status='active'::public.cohort_membership_status;if v_member_count>=v_capacity then raise exception 'Selected cohort is full';end if;insert into public.programme_enrolments(student_id,programme_id,application_id,status,created_by) values(v_student_id,v_programme_id,p_application_id,'active'::public.programme_enrolment_status,p_reviewer_id) on conflict(student_id,programme_id) where status='active' do nothing;insert into public.cohort_students(cohort_id,student_id,status,assigned_by) values(v_cohort_id,v_student_id,'active'::public.cohort_membership_status,p_reviewer_id) on conflict(cohort_id,student_id) do update set status='active'::public.cohort_membership_status,left_at=null,assigned_by=excluded.assigned_by,updated_at=now();end loop;
update public.enrolment_applications set status='approved'::public.enrolment_application_status,reviewed_by=p_reviewer_id,reviewed_at=now(),review_notes=nullif(btrim(p_review_notes),''),approved_student_id=v_student_id where id=p_application_id;return v_student_id;end;$$;
revoke all on function public.approve_enrolment_application(uuid,jsonb,uuid,text) from public,anon,authenticated;grant execute on function public.approve_enrolment_application(uuid,jsonb,uuid,text) to service_role;
